Repository nitrado/connqc, pull requests merged in 2023-06, with the labels that each got.

#12 Rename quality control to quality checker
  README.md
  cmd/connqc/main.go
Labels: documentation, enhancement

#19 refactor: remove unused concept of multiple TCP server listeners
  go.mod
  go.sum
  tcp/server.go
  tcp/server_test.go
Labels: enhancement, dependencies

#18 chore(deps): update golangci-lint to v1.53.3 and configure depguard
  .github/workflows/ci.yml
  .golangci.yml
Labels: dependencies
